### ISSUE TITLE
"Missing "./server-renderer" specifier in "vue" package" error on Nuxt 3 build

### ISSUE THREAD

**Issue by vlad-maleev** [Binaryify/vue-custom-scrollbar#97]
I use this package on Nuxt 3 app. It worked until 3.2 version released. Now on build it gives this error: 
"Missing "./server-renderer" specifier in "vue" package"

Is this possible to be resolved or should I consider some other package for custom scrollbar?

Here is the [reproduction](https://stackblitz.com/edit/github-wscyrw)

`[commonjs--resolver] Missing "./server-renderer" specifier in "vue" package

 ERROR  Missing "./server-renderer" specifier in "vue" package                                                                                 18:42:19

  at e (node_modules/vite/dist/node/chunks/dep-9912c491.js:14845:25)
  at n (node_modules/vite/dist/node/chunks/dep-9912c491.js:14845:627)
  at o (node_modules/vite/dist/node/chunks/dep-9912c491.js:14845:1276)
  at resolveExports (node_modules/vite/dist/node/chunks/dep-9912c491.js:22032:20)
  at resolveDeepImport (node_modules/vite/dist/node/chunks/dep-9912c491.js:22051:31)
  at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-9912c491.js:21736:20)
  at Object.resolveId (node_modules/vite/dist/node/chunks/dep-9912c491.js:21487:28)
  at Object.handler (node_modules/vite/dist/node/chunks/dep-9912c491.js:44849:19)
  at node_modules/rollup/dist/es/shared/rollup.js:24011:40
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/rollup.js:23911:28)
  at async resolveId (node_modules/rollup/dist/es/shared/rollup.js:22855:26)
  at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/rollup.js:23119:15)
  at async Object.resolveId (node_modules/vite/dist/node/chunks/dep-9912c491.js:7972:10)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/rollup.js:23911:28)
  at async resolveId (node_modules/rollup/dist/es/shared/rollup.js:22855:26)
  at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/rollup.js:23119:15)
  at async node_modules/rollup/dist/es/shared/rollup.js:23407:50`

**Comment by alfathony** [comment]
i have same issue

**Comment by wladyslaw-malejew** [comment]
@alfathony did you find some workaround?

**Comment by flyher** [comment]
@vlad-maleev 
This component only works fine on Vue2, it is not adapted to Vue3.
